CHECKLIST_SECTIONS = [
    {
        "name": "1. Basic Concepts & Types",
        "items": [
            "Create and reassign variables",
            "Copy values (x = y)",
            "Know valid and invalid variable names",
            "Use int, float, str, bool",
            "Inspect types using type()",
            "Cast using int(), float(), str()",
            "Use arithmetic operators",
            "Use comparison operators",
            "Use boolean operators",
            "Understand truthiness and falsy values",
        ],
    },
    {
        "name": "2. Flow Control",
        "items": [
            "Write if/elif/else blocks",
            "Nested if statements",
            "Boolean expressions in conditions",
            "Use while loops",
            "Print inside vs after a while loop",
            "Recognize infinite loops",
            "Use break inside loops",
            "Use for loops with range()",
            "Understand range(start, stop, step)",
            "Use continue to skip iterations",
        ],
    },
    {
        "name": "3. Collections",
        "items": [
            "Create lists and index elements",
            "Use negative indices",
            "Use len()",
            "Use list methods: append, insert, remove, pop",
            "Slice lists",
            "Understand list mutability",
            "Work with tuples and immutability",
            "Tuple packing/unpacking",
            "Index and slice strings",
            "Understand string immutability",
        ],
    },
    {
        "name": "4. Functions",
        "items": [
            "Define and call functions",
            "Use parameters",
            "Use default parameters",
            "Return values",
            "Functions without return → None",
            "Local vs global scope",
            "Variables inside functions not visible outside",
        ],
    },
    {
        "name": "5. Exceptions",
        "items": [
            "Know common exceptions",
            "Recognize NameError, IndexError, KeyError",
            "Write try/except",
            "Catch specific errors",
            "Use generic except",
            "Recognize basic error messages",
        ],
    },
    {
        "name": "6. Modules",
        "items": [
            "Import module",
            "from module import name",
            "Use functions from modules",
            "Understand module namespaces",
        ],
    },
    {
        "name": "7. Basic OOP",
        "items": [
            "Define a class",
            "Create objects",
            "Work with instance attributes",
            "Write methods with self",
            "Use __init__",
            "Class vs instance attributes",
            "Assignment creates instance attribute",
            "Subclass: class B(A)",
            "Inheritance of methods",
            "Override methods",
        ],
    },
    {
        "name": "8. Input & Output",
        "items": [
            "Use print()",
            "Use input()",
            "Convert input to integers",
        ],
    },
    {
        "name": "9. Misc & Error Understanding",
        "items": [
            "Write comments",
            "Indentation rules",
            "Recognize undefined variable errors",
            "Follow code execution order",
            "Trace values through loops",
        ],
    },
]
